from __future__ import annotations

"""Compatibility wrapper for the refactored QSAR regression service."""

from chem_inf_widgets.chemcore.qsar.algorithms import (
    QSARRunConfig,
    TORCH_AVAILABLE,
    TorchRegressor,
    _build_modeling_pipeline,
    _make_safe_regressor,
    _run_auto_qsar_model_selection,
    available_algorithms,
    build_run_config,
)
from chem_inf_widgets.chemcore.qsar.applicability_domain import build_applicability_domain_table
from chem_inf_widgets.chemcore.qsar.dataset import (
    LEAKY_OR_NON_DESCRIPTOR_ATTRIBUTE_NAMES,
    RDKit_DESCRIPTOR_NAMES,
    TARGET_COLUMN_CANDIDATES,
    _rdkit_descriptor_row,
    cap_qsar_descriptor_matrix,
    clean_qsar_descriptor_matrix,
    find_name_var,
    find_smiles_var,
    prepare_qsar_model_matrix,
)
from chem_inf_widgets.chemcore.qsar.diagnostics import (
    CompoundPreview,
    DiagnosticDatasetPayload,
    DiagnosticPlotData,
    DiagnosticPlotSpec,
    DiagnosticSeries,
    FeatureInspectionPayload,
    SelectionGalleryPayload,
    SelectionPublishPayload,
    _transform_features,
    build_compound_previews,
    build_diagnostic_plot_spec,
    build_feature_inspection_payload,
    build_selection_gallery_payload,
    build_selection_publish_payload,
    compute_coef_stats,
    compute_vif,
    diagnostic_payloads_from_result,
    extract_descriptor_coefficients,
    lasso_selection_indices,
    prepare_diagnostic_plot_data,
    rectangle_selection_indices,
    selection_overlay_offsets,
    selection_status_text,
)
from chem_inf_widgets.chemcore.qsar.regression_service import run_qsar_regression
from chem_inf_widgets.chemcore.qsar.reporting import (
    ReportContext,
    build_cancelled_status_text,
    build_completed_status_text,
    build_error_status_text,
    build_pdf_export_empty_status_text,
    build_pdf_export_error_status_text,
    build_pdf_export_success_status_text,
    build_pdf_report_figure_from_context,
    build_pdf_report_text,
    build_pdf_report_text_from_context,
    build_report_context,
    build_report_html,
    build_report_html_from_context,
    build_waiting_report_html,
    build_waiting_status_text,
    collect_pdf_export_figures,
)
from chem_inf_widgets.chemcore.qsar.validation import build_qsar_modeling_summary_table

__all__ = [
    "CompoundPreview",
    "DiagnosticDatasetPayload",
    "DiagnosticPlotData",
    "DiagnosticPlotSpec",
    "DiagnosticSeries",
    "FeatureInspectionPayload",
    "LEAKY_OR_NON_DESCRIPTOR_ATTRIBUTE_NAMES",
    "QSARRunConfig",
    "RDKit_DESCRIPTOR_NAMES",
    "ReportContext",
    "SelectionGalleryPayload",
    "SelectionPublishPayload",
    "TARGET_COLUMN_CANDIDATES",
    "TORCH_AVAILABLE",
    "TorchRegressor",
    "_build_modeling_pipeline",
    "_make_safe_regressor",
    "_rdkit_descriptor_row",
    "_run_auto_qsar_model_selection",
    "_transform_features",
    "available_algorithms",
    "build_applicability_domain_table",
    "build_cancelled_status_text",
    "build_completed_status_text",
    "build_compound_previews",
    "build_diagnostic_plot_spec",
    "build_error_status_text",
    "build_feature_inspection_payload",
    "build_pdf_export_empty_status_text",
    "build_pdf_export_error_status_text",
    "build_pdf_export_success_status_text",
    "build_pdf_report_figure_from_context",
    "build_pdf_report_text",
    "build_pdf_report_text_from_context",
    "build_qsar_modeling_summary_table",
    "build_report_context",
    "build_report_html",
    "build_report_html_from_context",
    "build_run_config",
    "build_selection_gallery_payload",
    "build_selection_publish_payload",
    "build_waiting_report_html",
    "build_waiting_status_text",
    "cap_qsar_descriptor_matrix",
    "clean_qsar_descriptor_matrix",
    "collect_pdf_export_figures",
    "compute_coef_stats",
    "compute_vif",
    "diagnostic_payloads_from_result",
    "extract_descriptor_coefficients",
    "find_name_var",
    "find_smiles_var",
    "lasso_selection_indices",
    "prepare_diagnostic_plot_data",
    "prepare_qsar_model_matrix",
    "rectangle_selection_indices",
    "run_qsar_regression",
    "selection_overlay_offsets",
    "selection_status_text",
]
