"""QSAR core utilities (dataset prep, feature filtering, MLR selection, applicability domain)."""

from .dataset import (
    LEAKY_OR_NON_DESCRIPTOR_ATTRIBUTE_NAMES,
    RDKit_DESCRIPTOR_NAMES,
    TARGET_COLUMN_CANDIDATES,
    _rdkit_descriptor_row,
    cap_qsar_descriptor_matrix,
    clean_qsar_descriptor_matrix,
    find_name_var,
    find_smiles_var,
    prepare_qsar_model_matrix,
)
from .algorithms import (
    QSARRunConfig,
    TORCH_AVAILABLE,
    TorchRegressor,
    _build_modeling_pipeline,
    _make_safe_regressor,
    _run_auto_qsar_model_selection,
    available_algorithms,
    build_run_config,
)
from .reporting import (
    ReportContext,
    build_cancelled_status_text,
    build_completed_status_text,
    build_error_status_text,
    build_pdf_export_empty_status_text,
    build_pdf_export_error_status_text,
    build_pdf_export_success_status_text,
    build_pdf_report_figure_from_context,
    build_pdf_report_text,
    build_pdf_report_text_from_context,
    build_report_context,
    build_report_html,
    build_report_html_from_context,
    build_waiting_report_html,
    build_waiting_status_text,
    collect_pdf_export_figures,
)

__all__ = [
    "LEAKY_OR_NON_DESCRIPTOR_ATTRIBUTE_NAMES",
    "QSARRunConfig",
    "RDKit_DESCRIPTOR_NAMES",
    "ReportContext",
    "TARGET_COLUMN_CANDIDATES",
    "TORCH_AVAILABLE",
    "TorchRegressor",
    "_build_modeling_pipeline",
    "_make_safe_regressor",
    "_run_auto_qsar_model_selection",
    "_rdkit_descriptor_row",
    "available_algorithms",
    "build_cancelled_status_text",
    "build_completed_status_text",
    "build_error_status_text",
    "build_pdf_export_empty_status_text",
    "build_pdf_export_error_status_text",
    "build_pdf_export_success_status_text",
    "build_pdf_report_figure_from_context",
    "build_pdf_report_text",
    "build_pdf_report_text_from_context",
    "build_report_context",
    "build_report_html",
    "build_report_html_from_context",
    "build_run_config",
    "build_waiting_report_html",
    "build_waiting_status_text",
    "cap_qsar_descriptor_matrix",
    "clean_qsar_descriptor_matrix",
    "collect_pdf_export_figures",
    "find_name_var",
    "find_smiles_var",
    "prepare_qsar_model_matrix",
]
