from __future__ import annotations


CATEGORIES = {
    "core": {
        "title": "Cheminf - Core",
        "description": "Import, export, curate, standardize, retrieve, and inspect molecular data.",
    },
    "search-analysis": {
        "title": "Cheminf - Search Analysis",
        "description": "Calculate molecular representations and investigate chemical similarity and series.",
    },
    "filters-alerts": {
        "title": "Cheminf - Filters Alerts",
        "description": "Apply drug-likeness rules and structural-alert screening.",
    },
    "qsar": {
        "title": "Cheminf - QSAR",
        "description": "Prepare, train, validate, explain, report, and deploy QSAR/QSPR models.",
    },
    "reactions": {
        "title": "Cheminf - Reactions",
        "description": "Apply reaction rules, inspect reactions, and enumerate virtual products.",
    },
}


def widget(
    slug,
    name,
    category,
    module,
    icon,
    description,
    inputs,
    outputs,
    overview,
    controls,
    workflow,
    note,
):
    return {
        "slug": slug,
        "name": name,
        "category": category,
        "module": module,
        "icon": icon,
        "description": description,
        "inputs": inputs,
        "outputs": outputs,
        "overview": overview,
        "controls": controls,
        "workflow": workflow,
        "note": note,
    }


WIDGETS = [
    widget(
        "molecule-import-hub",
        "Molecule Import Hub",
        "core",
        "ow_molecule_import_hub",
        "icons/input_output/owmolimport.png",
        "Import molecules from CSV, TSV, SMI, TXT, or SDF files with automatic structure-column detection and an auditable report.",
        [],
        [("Data", "Table"), ("Molecules", "list"), ("Accepted Data", "Table"), ("Accepted Molecules", "list"), ("Rejected Records", "Table"), ("Import Report", "Table"), ("Failed Records", "Table"), ("Import Summary", "Table"), ("Curation Summary", "Table")],
        "Molecule Import Hub is the recommended entry point for molecular files. It detects delimiters and structure columns, parses molecules, preserves source fields, and separates accepted and rejected records so import failures are visible.",
        ["Choose an input file and confirm the detected format.", "Select the SMILES and optional name columns.", "Enable sanitization, hydrogen removal, and duplicate checks.", "Run the import and inspect the report before continuing."],
        "Molecule Import Hub → Molecule QC Dashboard → Mol Standardizer",
        "Use the accepted outputs for curated workflows and retain the reports for provenance.",
    ),
    widget(
        "molecule-export-hub",
        "Molecule Export Hub",
        "core",
        "ow_molecule_export_hub",
        "icons/input_output/owmolexport.png",
        "Export molecular tables or molecule collections to CSV, TSV, TXT, SMI, or SDF with an audit report.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Export Report", "Table"), ("Failed Records", "Table"), ("Export Summary", "Table")],
        "Molecule Export Hub converts workflow results into common chemistry file formats while recording which rows were written and which conversions failed.",
        ["Choose the output path and format.", "Map structure and name columns.", "Choose whether to sanitize and use canonical SMILES.", "Select property, metadata, and header options, then export."],
        "Mol Standardizer → Molecule Export Hub",
        "Inspect Failed Records whenever the exported row count differs from the input row count.",
    ),
    widget(
        "sdf-reader",
        "SDF Reader",
        "core",
        "ow_sdf_reader",
        "icons/input_output/owsdfreaderwidget.png",
        "Read Structure Data Files and expose molecules as an Orange table and chemical objects.",
        [],
        [("Data", "Table"), ("Molecules", "list")],
        "SDF Reader loads structures and selected SDF properties. It can sanitize molecules and remove explicit hydrogens during import.",
        ["Select an SDF or SD file.", "Choose whether molecules are sanitized and hydrogens removed.", "Refresh and select the SDF properties to preserve.", "Load the file and connect either output downstream."],
        "SDF Reader → Mol Standardizer → Molecular Viewer",
        "Use Molecule Import Hub when you need row-level import and curation reports.",
    ),
    widget(
        "sdf-writer",
        "SDF Writer",
        "core",
        "ow_sdf_writer",
        "icons/input_output/owsdfwriterwidget.png",
        "Write an Orange molecular table or molecule collection to an SDF file.",
        [("Data", "Table"), ("Molecules", "list")],
        [],
        "SDF Writer serializes structures and optional table properties to a user-selected SDF path.",
        ["Choose the output SDF path.", "Enable or disable writing properties.", "Select the properties to include.", "Write the connected molecules to disk."],
        "Mol Standardizer → SDF Writer",
        "The widget writes directly to disk and therefore has no Orange output signal.",
    ),
    widget(
        "chembl-bioactivity-retriever",
        "ChEMBL Bioactivity Retriever",
        "core",
        "ow_chembl_dataretriever",
        "icons/data_retrieval/chembl.png",
        "Fetch ChEMBL bioactivity records and drug-design properties for downstream curation and modeling.",
        [],
        [("Bioactivity Data", "Table")],
        "The retriever queries the ChEMBL web service for activity records and returns an Orange table containing compound identifiers, structures, assay context, and activity fields.",
        ["Enter or select the ChEMBL target criteria.", "Configure activity and result limits.", "Start retrieval and monitor status messages.", "Inspect endpoint, unit, relation, and assay fields before modeling."],
        "ChEMBL Bioactivity Retriever → QSAR Dataset Builder → Mol Standardizer",
        "An internet connection is required. ChEMBL records should be curated before QSAR training.",
    ),
    widget(
        "chembl-browser",
        "ChEMBL Browser",
        "core",
        "ow_chembl_browser",
        "icons/data_retrieval/owchemblbrowserwidget.png",
        "Interactively search ChEMBL targets, assays, activities, and compounds and send selected records into Orange.",
        [],
        [("Data", "Table"), ("Molecules", "list"), ("Selected Data", "Table"), ("Selected Molecules", "list")],
        "ChEMBL Browser provides an exploratory interface for target and compound discovery. Full result sets and current selections can be sent as tables or molecule objects.",
        ["Search for a target and limit the returned target list.", "Filter assays by confidence and type.", "Choose activity type and result limits.", "Select properties and bioactivity fields for the exported table."],
        "ChEMBL Browser → Molecule QC Dashboard → QSAR Dataset Builder",
        "An internet connection is required. Prefer selected outputs when only a reviewed subset should continue.",
    ),
    widget(
        "molecule-qc-dashboard",
        "Molecule QC Dashboard",
        "core",
        "ow_molecule_qc_dashboard",
        "icons/standardization_filtering/owmolocwidget.png",
        "Detect invalid structures, fragments, duplicates, charges, metals, stereochemistry gaps, and other molecular quality issues.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Modeling Data", "Table"), ("QC Annotated Data", "Table"), ("Clean Data", "Table"), ("Problem Data", "Table"), ("Rejected Data", "Table"), ("QC Report", "Table"), ("QC Summary", "Table"), ("Curation Summary", "Table"), ("QC Annotated Molecules", "list"), ("Clean Molecules", "list"), ("Problem Molecules", "list"), ("Rejected Molecules", "list")],
        "The dashboard applies reproducible molecular quality checks and partitions records by severity. Its reports preserve the reason each molecule was accepted, flagged, or rejected.",
        ["Choose the duplicate identity rule.", "Set molecular-weight, heavy-atom, and fragment limits.", "Enable metal, isotope, radical, charge, and stereochemistry checks.", "Review summary counts before using Clean Data or Modeling Data."],
        "Molecule Import Hub → Molecule QC Dashboard → Mol Standardizer",
        "Quality flags are screening signals; review flagged chemistry rather than treating every flag as an automatic exclusion.",
    ),
    widget(
        "molecular-viewer",
        "Molecular Viewer",
        "core",
        "ow_mol_viewer",
        "icons/editors_viewers/owmolviewerwidget.png",
        "Display scalable two-dimensional molecular cards with optional substructure highlighting.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Selected index", "int")],
        "Molecular Viewer renders a virtualized gallery for large molecular collections. It uses structure and highlight fields from upstream search widgets and reports the selected row index.",
        ["Choose the number of cards per row.", "Adjust card size and rendering batch size.", "Inspect highlighted substructures and available properties.", "Select a card to communicate its row index."],
        "Substructure & Similarity Search → Molecular Viewer",
        "For side-by-side transformations use Pair Viewer; for a single detailed record use Compound Detail Card.",
    ),
    widget(
        "mol-editor",
        "Mol Editor",
        "core",
        "ow_mol_editor",
        "icons/editors_viewers/owmoleditorwidget.png",
        "Draw or edit molecular structures in the embedded Ketcher-based editor.",
        [],
        [],
        "Mol Editor is the primary structure editor for creating query molecules and small molecular records inside Orange. It reuses the package's embedded Ketcher implementation.",
        ["Draw atoms, bonds, rings, and stereochemistry.", "Import or paste a supported structure representation.", "Clean or validate the current drawing.", "Use the editor in query-building and database-creation workflows."],
        "Mol Editor → Substructure & Similarity Search",
        "The compatibility wrapper delegates its signals and behavior to the embedded molecular editor implementation.",
    ),
    widget(
        "mol-standardizer",
        "Mol Standardizer",
        "core",
        "ow_mol_standardizer",
        "icons/standardization_filtering/owmolstandardizerwidget.png",
        "Standardize molecular structures with RDKit MolStandardize while retaining audit information.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Modeling Data", "Table"), ("Data", "Table"), ("Molecules", "list"), ("QSAR-ready Data", "Table"), ("QSAR-ready Molecules", "list"), ("Standardization Failed Data", "Table"), ("Standardization Failed Molecules", "list"), ("Standardization Report", "Table"), ("Curation Summary", "Table")],
        "Mol Standardizer applies configurable cleanup, normalization, metal disconnection, fragment selection, reionization, and uncharging operations. It preserves failed records and a transformation report.",
        ["Select a standardization profile or individual operations.", "Configure sanitization before and after standardization.", "Choose whether standardized SMILES replace or supplement source values.", "Inspect failed records and the Standardization Report."],
        "Molecule QC Dashboard → Mol Standardizer → Fingerprint Generator",
        "Use the same profile on training and prediction data to keep molecular representations consistent.",
    ),
    widget(
        "compound-detail-card",
        "Compound Detail Card",
        "core",
        "ow_compound_detail_card",
        "icons/editors_viewers/owcompounddetailcardwidget.svg",
        "Inspect one compound with structure, properties, motifs, fragments, scaffold context, and similar reference compounds.",
        [("Data", "Table"), ("Molecules", "list"), ("Reference Data", "Table")],
        [("Selected Compound", "Table"), ("Similar Compounds", "Table"), ("Matched Fragments", "Table"), ("Detected Motifs", "Table"), ("Motif Queries", "Table"), ("Query Molecule", "ChemMol"), ("Fragment Queries", "Table"), ("Scaffold Query", "Table"), ("Search Profile", "Table")],
        "Compound Detail Card is a FAIRMol-style inspection and search-launch widget. It summarizes the selected compound and emits motif-, fragment-, and scaffold-derived queries.",
        ["Map structure and name fields.", "Select the compound to inspect.", "Choose the number of similar reference compounds.", "Select motifs and AND/OR logic for downstream searches."],
        "Molecular Viewer → Compound Detail Card → PharmaFP Search",
        "Connect Reference Data to enable local similarity results.",
    ),
    widget(
        "substructure-similarity-search",
        "Substructure & Similarity Search",
        "search-analysis",
        "ow_substructure_search",
        "icons/standardization_filtering/owsubstructurewidget.png",
        "Filter a compound table by a query structure using substructure matching or fingerprint similarity.",
        [("Query", "str"), ("Query Data", "Table"), ("Query Molecule", "ChemMol"), ("Compounds", "Table")],
        [("Filtered Compounds", "Table")],
        "The widget accepts several query representations and searches a SMILES-bearing compound table. Matching atom indices can be appended for visual highlighting.",
        ["Choose substructure or similarity mode.", "Provide a query through one of the query inputs.", "Set fingerprint type and similarity threshold when applicable.", "Enable atom highlighting and run the search."],
        "Mol Editor → Substructure & Similarity Search → Molecular Viewer",
        "Use Similarity Search when separate query and reference libraries require ranked nearest neighbors.",
    ),
    widget(
        "fingerprint-generator",
        "Fingerprint Generator",
        "search-analysis",
        "ow_fingerprint_generator",
        "icons/descriptors/owmolfingerprintwidget.png",
        "Compute Morgan, RDKit, or MACCS structural fingerprints from molecular tables or molecule objects.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Fingerprints", "Table"), ("Molecules", "list")],
        "Fingerprint Generator converts structures into numerical bit vectors for similarity, diversity, clustering, chemical-space, and machine-learning workflows.",
        ["Choose Morgan, RDKit, or MACCS fingerprints.", "Configure bit size and Morgan radius.", "Select the SMILES field and metadata to retain.", "Choose whether to emit molecules and append numeric descriptors."],
        "Mol Standardizer → Fingerprint Generator → Similarity Search",
        "Keep fingerprint settings identical across all branches that will be compared or modeled together.",
    ),
    widget(
        "rdkit-descriptors",
        "RDKit Descriptors",
        "search-analysis",
        "ow_rdkit_descriptors",
        "icons/descriptors/owmoldescriptorwidget.png",
        "Compute categorized RDKit molecular descriptors from tables or molecule objects.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Data", "Table"), ("Molecules", "list")],
        "RDKit Descriptors offers fast, built-in descriptor calculation with presets and category selection. Results can be written to a table and optionally attached to molecule objects.",
        ["Select a descriptor preset.", "Enable descriptor categories or individual descriptors.", "Choose whether values are written back to molecule objects.", "Run automatically or apply changes manually."],
        "Mol Standardizer → RDKit Descriptors → QSAR Descriptor Explorer",
        "Use Mol Descriptors 2 when a broader Mordred descriptor space is required.",
    ),
    widget(
        "mol-descriptors-2",
        "Mol Descriptors 2",
        "search-analysis",
        "ow_mol_descriptor",
        "icons/descriptors/owmoldescriptorwidget.png",
        "Compute Mordred descriptors from molecular tables or molecule objects.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Data", "Table"), ("Molecules", "list")],
        "Mol Descriptors 2 exposes Mordred descriptor presets, categories, and groups and supports parallel calculation for larger datasets.",
        ["Select a preset, categories, groups, or individual descriptors.", "Choose whether three-dimensional descriptors are ignored.", "Set the number of worker processes.", "Choose whether results are also written to molecule objects."],
        "Mol Standardizer → Mol Descriptors 2 → QSAR Descriptor Explorer",
        "Mordred is an optional dependency; install the descriptors extra before using this widget.",
    ),
    widget(
        "diversity-picker",
        "Diversity Picker",
        "search-analysis",
        "ow_diversity_picker",
        "icons/analysis/owdiversitypickerwidget.svg",
        "Select a structurally diverse subset using MaxMin, sphere exclusion, or Butina clustering.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Selected Data", "Table"), ("Annotated Data", "Table"), ("Remainder Data", "Table"), ("Inspected Data", "Table"), ("Inspected Molecules", "list"), ("Selected Molecules", "list"), ("Remainder Molecules", "list")],
        "Diversity Picker computes internal fingerprints, selects representative compounds, and provides a two-dimensional inspection view with selected and remainder partitions.",
        ["Choose the selection algorithm.", "Set subset size and random seed.", "Configure sphere radius or Butina threshold when applicable.", "Inspect selected compounds in the chemical-space view."],
        "Mol Standardizer → Diversity Picker → Molecular Viewer",
        "MaxMin is the recommended deterministic starting point for representative subset selection.",
    ),
    widget(
        "scaffold-analysis",
        "Scaffold Analysis",
        "search-analysis",
        "ow_scaffold_analysis",
        "icons/analysis/owscaffoldanalysiswidget.svg",
        "Annotate molecules with Murcko scaffolds and summarize scaffold frequencies.",
        [("Data", "Table"), ("Molecules", "list")],
        [("Annotated Data", "Table"), ("Scaffold Summary", "Table"), ("Annotated Molecules", "list"), ("Selected Scaffold", "Table")],
        "Scaffold Analysis identifies core frameworks, appends scaffold annotations, summarizes series sizes, and lets a selected scaffold continue downstream.",
        ["Select the structure field.", "Choose the scaffold summary representation.", "Decide whether acyclic molecules are included.", "Set the displayed top-N scaffolds and select a scaffold."],
        "Mol Standardizer → Scaffold Analysis → R-Group Decomposition",
        "Use Scaffold Splitter when the objective is chemically separated model evaluation rather than series annotation.",
    ),
    widget(
        "activity-cliff-finder",
        "Activity Cliff Finder",
        "search-analysis",
        "ow_activity_cliff_finder",
        "icons/analysis/owactivityclifffinderwidget.png",
        "Find highly similar molecular pairs with large activity differences.",
        [("Data", "Table")],
        [("Cliff Pairs", "Table"), ("Cliff Compounds", "Table"), ("Scaffold Summary", "Table")],
        "Activity Cliff Finder calculates pair similarity and activity differences to identify abrupt structure-activity changes and summarize the scaffolds involved.",
        ["Select structure and activity fields.", "Set the minimum similarity.", "Set the activity fold threshold and scale interpretation.", "Limit the number of reported pairs."],
        "QSAR Dataset Builder → Activity Cliff Finder → Pair Viewer",
        "Activity cliffs are sensitive to assay consistency and activity-unit handling; curate the activity table first.",
    ),
    widget(
        "pair-viewer",
        "Pair Viewer",
        "search-analysis",
        "ow_pair_viewer",
        "icons/editors_viewers/owpairviewerwidget.png",
        "Inspect paired compounds side by side with activity, similarity, and transformation context.",
        [("Data", "Table")],
        [("Selected Pairs", "Table"), ("Pair Compounds", "Table")],
        "Pair Viewer maps two structure columns and optional pair metrics into a synchronized side-by-side molecular display.",
        ["Map left and right structure columns.", "Map optional names, activities, similarity, ratio, and cliff score.", "Browse pair records and compare highlighted changes.", "Send the selected pair or its compounds downstream."],
        "Activity Cliff Finder → Pair Viewer → Compound Detail Card",
        "The viewer also works well for original-versus-standardized molecular pairs.",
    ),
    widget(
        "scaffold-splitter",
        "Scaffold Splitter",
        "search-analysis",
        "ow_scaffold_splitter",
        "icons/analysis/owscaffoldsplitterwidget.svg",
        "Split a dataset into train, validation, and test partitions using scaffold-aware, random, or activity-stratified logic.",
        [("Data", "Table")],
        [("Train Data", "Table"), ("Validation Data", "Table"), ("Test Data", "Table"), ("Split Summary", "Table")],
        "Scaffold Splitter supports chemically realistic evaluation by keeping related scaffolds together while assigning records to model-development partitions.",
        ["Select structure and optional target fields.", "Choose scaffold, random, or activity-stratified splitting.", "Set scaffold representation and partition fractions.", "Set the random seed and review Split Summary."],
        "QSAR Dataset Builder → Scaffold Splitter → QSAR/QSPR Model Hub",
        "Scaffold splitting is usually more demanding and more realistic than a random split for molecular models.",
    ),
    widget(
        "similarity-search",
        "Similarity Search",
        "search-analysis",
        "ow_similarity_search",
        "icons/standardization_filtering/owsimilaritysearchwidget.svg",
        "Return ranked nearest neighbors for query compounds in a reference molecular library.",
        [("Query Data", "Table"), ("Reference Data", "Table")],
        [("Neighbor Pairs", "Table"), ("Hit Compounds", "Table")],
        "Similarity Search compares two molecular tables with configurable fingerprints and returns pairwise scores plus the matching reference compounds.",
        ["Map query and reference structure fields.", "Choose fingerprint type, radius, and bit count.", "Set neighbors per query and minimum similarity.", "Run and inspect ranked pairs."],
        "Query Data ─┐\n            ├→ Similarity Search → Molecular Viewer\nReference ──┘",
        "Generate query and reference structures with the same standardization policy.",
    ),
    widget(
        "r-group-decomposition",
        "R-Group Decomposition",
        "search-analysis",
        "ow_rgroup_decomposition",
        "icons/analysis/owrgroupdecompositionwidget.svg",
        "Break a coherent compound series into a shared core and R-group substituents.",
        [("Data", "Table")],
        [("R-Group Table", "Table"), ("Matched Data", "Table"), ("Unmatched Data", "Table")],
        "R-Group Decomposition applies a user-defined or inferred core to a series and creates columns for substituent positions while separating unmatched records.",
        ["Select the molecular structure field.", "Enter or edit the core query.", "Run decomposition and inspect substituent assignments.", "Review unmatched molecules before interpreting the series."],
        "Scaffold Analysis → R-Group Decomposition → Data Table",
        "Results are most interpretable when the input already represents one coherent chemical series.",
    ),
    widget(
        "matched-molecular-pairs",
        "Matched Molecular Pairs",
        "search-analysis",
        "ow_matched_molecular_pairs",
        "icons/analysis/owmatchedmolecularpairswidget.svg",
        "Find molecule pairs that share a common core and differ by a localized transformation.",
        [("Data", "Table")],
        [("Pair Table", "Table"), ("Pair Compounds", "Table")],
        "Matched Molecular Pairs extracts local structural transformations and optional property changes for systematic SAR analysis.",
        ["Select the structure field.", "Select an optional property field.", "Set the minimum shared atom count.", "Limit the number of generated pairs."],
        "Mol Standardizer → Matched Molecular Pairs → Pair Viewer",
        "Use Activity Cliff Finder when high similarity plus a large activity gap is the primary criterion.",
    ),
    widget(
        "drug-filter",
        "Drug Filter",
        "filters-alerts",
        "ow_drug_filter",
        "icons/standardization_filtering/owdrugfilterwidget.png",
        "Apply Lipinski, Veber, QED, and PAINS-based drug-likeness screening to molecular tables.",
        [("Input Table", "Table")],
        [("Filtered Compounds", "Table")],
        "Drug Filter calculates practical medicinal-chemistry properties, evaluates selectable rule sets, and can highlight PAINS substructures.",
        ["Choose the rule set: Lipinski, Veber, combined, or none.", "Choose whether to forward all, passing, or failing molecules.", "Enable PAINS highlighting when required.", "Provide an alternate PAINS pattern file only when necessary."],
        "Mol Standardizer → Drug Filter → Molecular Viewer",
        "Drug-likeness and structural alerts are prioritization aids, not automatic medicinal-chemistry decisions.",
    ),
    widget(
        "qsar-dataset-builder",
        "QSAR Dataset Builder",
        "qsar",
        "ow_qsar_dataset_builder",
        "icons/modeling/ow_qsar_dataset_builder.png",
        "Curate activity records into a QSAR-ready table with pActivity conversion, duplicate aggregation, and reports.",
        [("Data", "Table")],
        [("QSAR Ready Data", "Table"), ("Rejected Records", "Table"), ("Curation Report", "Table"), ("Dataset Summary", "Table")],
        "QSAR Dataset Builder maps activity fields, normalizes concentration units into pActivity, handles relation qualifiers, filters endpoint types, and aggregates duplicate compounds.",
        ["Map structure, identifier, activity, unit, relation, and endpoint fields.", "Choose target endpoint and unit handling.", "Set relation and duplicate-aggregation policies.", "Optionally constrain the accepted pActivity range."],
        "ChEMBL Browser → QSAR Dataset Builder → Mol Descriptors 2",
        "Inspect Rejected Records and Curation Report before treating the result as model-ready.",
    ),
    widget(
        "descriptor-pre-selector",
        "Descriptor Pre-selector",
        "qsar",
        "ow_descriptor_filter",
        "icons/modeling/ow_descriptor_filter.png",
        "Remove descriptors with excessive missingness, low variance, or high inter-feature correlation.",
        [("Data", "Table")],
        [("Filtered Data", "Table"), ("Modeling Data", "Table"), ("Filter Report", "Table")],
        "Descriptor Pre-selector applies transparent unsupervised filters before model training and records the threshold and descriptor-count cascade.",
        ["Set the maximum missing fraction.", "Set the minimum variance.", "Choose Pearson or Spearman correlation and its threshold.", "Set feature-count safeguards and inspect Filter Report."],
        "QSAR Descriptor Explorer → Descriptor Pre-selector → QSAR/QSPR Model Hub",
        "Apply descriptor filtering inside cross-validation when estimating unbiased model performance.",
    ),
    widget(
        "qsar-descriptor-explorer",
        "QSAR Descriptor Explorer",
        "qsar",
        "ow_descriptor_explorer",
        "icons/descriptors/owmoldescriptorwidget.png",
        "Analyze descriptor categories, missingness, variance, and redundancy before QSAR modeling.",
        [("Data", "Table")],
        [("Filtered Data", "Table"), ("Descriptor Summary", "Table"), ("Category Summary", "Table"), ("Correlation Pairs", "Table"), ("Quality Report", "Table"), ("Report HTML", "str"), ("Report Markdown", "str")],
        "QSAR Descriptor Explorer profiles candidate descriptors and produces machine-readable summaries and reusable HTML or Markdown quality reports.",
        ["Map the target and identifier fields.", "Set missingness and low-variance thresholds.", "Set the high-correlation threshold.", "Review descriptor, category, pair, and quality summaries."],
        "Mol Descriptors 2 → QSAR Descriptor Explorer → Descriptor Pre-selector",
        "The explorer is intended for matrix diagnosis; use a model-aware selection method only within a validated training procedure.",
    ),
    widget(
        "applicability-domain",
        "Applicability Domain",
        "qsar",
        "ow_applicability_domain",
        "icons/analysis/owapplicabilitydomainwidget.svg",
        "Evaluate whether query compounds lie inside the descriptor-space domain represented by a reference set.",
        [("Data", "Table"), ("Reference Data", "Table")],
        [("Data Results", "Table"), ("Reference Results", "Table"), ("AD Summary", "Table")],
        "Applicability Domain combines Williams leverage, k-nearest-neighbor distance, and Mahalanobis distance diagnostics to flag extrapolative predictions.",
        ["Enable the required applicability-domain methods.", "Choose AND or OR combination logic.", "Configure kNN neighborhood and quantile.", "Configure Mahalanobis significance handling and run the analysis."],
        "Training descriptors ─┐\n                     ├→ Applicability Domain → QSAR Report Generator\nQuery descriptors ───┘",
        "Reference and query tables must share the same continuous descriptor definition and preprocessing.",
    ),
    widget(
        "qsar-model-hub",
        "QSAR/QSPR Model Hub",
        "qsar",
        "ow_qsar_model_hub",
        "icons/modeling/ow_qsar_model_hub.png",
        "Train regression models for activity or physicochemical properties from descriptor or fingerprint tables.",
        [("Data", "Table")],
        [("Model", "object"), ("Predictions", "Table"), ("Metrics", "Table"), ("Model Summary", "Table"), ("Selected Compounds", "Table")],
        "QSAR/QSPR Model Hub provides a central model-training workflow with train/test evaluation, cross-validation, optional hyperparameter optimization, feature selection, and model export.",
        ["Map target, identifier, and target unit.", "Choose the regression algorithm and split settings.", "Configure cross-validation and random state.", "Optionally enable optimization, feature selection, or top-model ensembling."],
        "Descriptor Pre-selector → QSAR/QSPR Model Hub → QSAR Validation Dashboard",
        "Keep external test data isolated from feature selection and hyperparameter optimization.",
    ),
    widget(
        "qsar-validation-dashboard",
        "QSAR Validation Dashboard",
        "qsar",
        "ow_qsar_validation_dashboard",
        "icons/modeling/ow_qsar_validation_dashboard.png",
        "Evaluate QSAR predictions, residuals, split-level metrics, and outlier records.",
        [("Predictions", "Table")],
        [("Validation Metrics", "Table"), ("Residual Diagnostics", "Table"), ("Outlier Records", "Table"), ("Validation Summary", "Table"), ("Selected Compounds", "Table")],
        "The dashboard detects observed, predicted, split, and identifier fields; computes regression diagnostics; and provides linked residual and outlier inspection.",
        ["Map observed and predicted value fields.", "Map optional split and identifier fields.", "Set residual and standardized-residual thresholds.", "Inspect plots, selected compounds, and output tables."],
        "QSAR/QSPR Model Hub → QSAR Validation Dashboard → QSAR Report Generator",
        "Report train, validation, and external-test metrics separately.",
    ),
    widget(
        "model-explanation",
        "Model Explanation",
        "qsar",
        "ow_model_explanation",
        "icons/modeling/ow_model_explanation.png",
        "Explain global feature importance and approximate local contributions for QSAR models.",
        [("Data", "Table"), ("Model", "object")],
        [("Feature Importance", "Table"), ("Local Contributions", "Table"), ("Feature Summary", "Table"), ("Explanation Summary", "Table")],
        "Model Explanation uses native model importances, linear coefficients, permutation importance, or a correlation fallback and summarizes influential features and compounds.",
        ["Map target and identifier fields.", "Choose the explanation method.", "Set the maximum displayed features.", "Connect a trained model or allow the widget to fit its fallback model."],
        "QSAR/QSPR Model Hub → Model Explanation → QSAR Report Generator",
        "Feature importance describes model behavior and does not establish a causal chemical mechanism.",
    ),
    widget(
        "qsar-report-generator",
        "QSAR Report Generator",
        "qsar",
        "ow_qsar_report_generator",
        "icons/modeling/ow_qsar_report_generator.png",
        "Assemble interactive QSAR diagnostics and reproducible Markdown, HTML, and PDF reports.",
        [("Dataset", "Table"), ("Metrics", "Table"), ("Predictions", "Table"), ("Validation Summary", "Table"), ("Feature Importance", "Table"), ("Model Summary", "Table"), ("AD Summary", "Table"), ("Explanation Summary", "Table")],
        [("Report Markdown", "str"), ("Report HTML", "str"), ("Report PDF Path", "str"), ("Report Sections", "Table"), ("Report Summary", "Table")],
        "QSAR Report Generator combines model, validation, applicability-domain, and explanation outputs into a structured report with observed-versus-predicted, residual, metric, and importance views.",
        ["Set report title, project, and author.", "Connect any available QSAR result tables.", "Choose the maximum preview rows.", "Generate, review, and export the report."],
        "QSAR Validation Dashboard ─┐\nModel Explanation ────────────┼→ QSAR Report Generator\nApplicability Domain ─────────┘",
        "A report is only as reliable as the validation design and provenance supplied to it.",
    ),
    widget(
        "qsar-prediction-packager",
        "QSAR Prediction Packager",
        "qsar",
        "ow_qsar_prediction_packager",
        "icons/modeling/ow_qsar_prediction_packager.png",
        "Apply a trained model to query compounds and create an auditable external-prediction package.",
        [("Model", "object"), ("Query Data", "Table"), ("Molecules", "list")],
        [("Predictions", "Table"), ("Feature Report", "Table"), ("Package Manifest", "Table"), ("Failed Records", "Table")],
        "QSAR Prediction Packager aligns query features with a trained model contract, predicts compatible rows, and records missing, extra, and failed features.",
        ["Connect a trusted trained model.", "Connect query descriptors or molecule objects.", "Configure identifier, target label, and prediction column.", "Choose whether input fields are retained and inspect the manifest."],
        "QSAR/QSPR Model Hub ─┐\n                     ├→ QSAR Prediction Packager\nQuery descriptors ───┘",
        "Only load serialized model packages from trusted sources, and reproduce training-time preprocessing for query data.",
    ),
    widget(
        "rdkit-reactor",
        "RDKit Reactor",
        "reactions",
        "ow_reactor",
        "icons/reactions/rdkit_reactor.jpg",
        "Apply one or more SMIRKS transformations to a pool of molecular reactants.",
        [("Molecules", "Table"), ("Reactions (SMIRKS) 1", "Table"), ("Reactions (SMIRKS) 2", "Table"), ("Reactions (SMIRKS) 3", "Table")],
        [("Products", "Table"), ("Log", "Table")],
        "RDKit Reactor repeatedly samples reactants and reaction rules, applies transformations, and records generated products and per-attempt status.",
        ["Set the random seed, number of steps, and draws.", "Set product and reaction-trial limits.", "Choose self-reaction, sanitization, uniqueness, and reactant-consumption policies.", "Configure pool expansion and inspect the reaction log."],
        "Reactants + SMIRKS rules → RDKit Reactor → Molecular Viewer",
        "Validate reaction rules and inspect sanitization failures before using generated products.",
    ),
    widget(
        "reaction-viewer",
        "Reaction Viewer",
        "reactions",
        "ow_reactionviewer",
        "icons/reactions/reactionviewer.png",
        "Display RDKit reaction depictions from a table and export them as PNG or SVG.",
        [("Data", "Table")],
        [],
        "Reaction Viewer reads a reaction-string column or composes reactions from reactant and product columns, then renders a configurable gallery with optional captions.",
        ["Choose a reaction column or reactant/product composition mode.", "Set image size, rows, and columns.", "Choose caption behavior and source field.", "Set export format and filename prefix."],
        "RDKit Reactor → Reaction Viewer",
        "The widget is viewer-oriented and writes exported images directly to disk.",
    ),
    widget(
        "reaction-enumerator",
        "Reaction Enumerator",
        "reactions",
        "ow_reaction_enumerator",
        "icons/reactions/owreactionenumeratorwidget.svg",
        "Enumerate virtual products from up to three reactant sets and a table of SMIRKS rules.",
        [("Reactants A", "Table"), ("Reactants B", "Table"), ("Reactants C", "Table"), ("Reactions", "Table")],
        [("Products", "Table"), ("Enumeration Summary", "Table")],
        "Reaction Enumerator applies compatible one-, two-, or three-component reaction rules to reagent combinations and limits output growth with a product cap.",
        ["Connect required reactant libraries.", "Connect a reaction-rule table.", "Set the maximum product count.", "Run enumeration and review the summary."],
        "Reactant libraries + Reactions → Reaction Enumerator → Drug Filter",
        "Enumeration can grow combinatorially; start with a conservative product limit and curated reagent sets.",
    ),
]

WIDGETS_BY_SLUG = {item["slug"]: item for item in WIDGETS}

